//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License Version 2.0, January 2004
//
// https://www.apache.org/licenses/LICENSE-2.0
//
//----------------------------------------

// winapi 导出函数定义下标

package winapi

const (
	cef_win_CreateRectRgn = iota
	cef_win_SetRectRgn
	cef_win_DeleteObject
	cef_win_CombineRgn
	cef_win_SetDraggableRegions
	cef_win_PtInRegion
	cef_win_ScreenToClient
	cef_win_ClientToScreen
	cef_win_DefWindowProc
	cef_win_DefSubclassProc
	cef_win_CreateRoundRectRgn
	cef_win_SetWindowRgn
	cef_win_SetCursor
	cef_win_LoadCursor
	cef_win_OnPaint
	cef_win_EndPaint
	cef_win_BeginPaint
	cef_win_Arc
	cef_win_AngleChord
	cef_win_CallNextHookEx
	cef_win_CallWindowProc
	cef_win_BitBlt
	cef_win_CreateBitmap
	cef_win_CreateBrushIndirect
	cef_win_CreateBrushWithRadialGradient
	cef_win_CreateCaret
	cef_win_CreateCompatibleBitmap
	cef_win_CreateCompatibleDC
	cef_win_CreateDIBitmap
	cef_win_CreateDIBSection
	cef_win_CreateEllipticRgn
	cef_win_CreateFontIndirect
	cef_win_CreateFontIndirectEx
	cef_win_CreateIconIndirect
	cef_win_CreatePalette
	cef_win_CreatePatternBrush
	cef_win_CreatePenIndirect
	cef_win_CreatePolygonRgn
	cef_win_DeleteCriticalSection
	cef_win_DeleteDC
	cef_win_DestroyCaret
	cef_win_DestroyCursor
	cef_win_DestroyIcon
	cef_win_DrawFrameControl
	cef_win_DrawFocusRect
	cef_win_DrawEdge
	cef_win_DrawText
	cef_win_EnableScrollBar
	cef_win_EnableWindow
	cef_win_EnterCriticalSection
	cef_win_EnumDisplayMonitors             // no impl
	cef_win_EnumFontFamilies                // no impl
	cef_win_EnumFontFamiliesEx              // no impl
	cef_win_EnumDisplayMonitorsCallbackFree // no impl
	cef_win_EnumFontFamiliesCallbackFree    // no impl
	cef_win_EnumFontFamiliesExCallbackFree  // no impl
	cef_win_Ellipse
	cef_win_EqualRgn
	cef_win_ExcludeClipRect
	cef_win_ExtCreatePen
	cef_win_ExtTextOut
	cef_win_ExtSelectClipRGN
	cef_win_FillRect
	cef_win_FillRgn
	cef_win_FloodFill
	cef_win_FrameRect
	cef_win_GetActiveWindow
	cef_win_GetBitmapBits
	cef_win_GetBkColor
	cef_win_GetCapture
	cef_win_GetCaretPos
	cef_win_GetClientRect
	cef_win_GetClipBox
	cef_win_GetClipRGN
	cef_win_GetCurrentObject
	cef_win_GetCursorPos
	cef_win_GetDC
	cef_win_GetDeviceCaps
	cef_win_GetDIBits
	cef_win_GetDoubleClickTime
	cef_win_GetFocus
	cef_win_GetFontLanguageInfo
	cef_win_GetForegroundWindow
	cef_win_GetIconInfo
	cef_win_GetKeyState
	cef_win_GetMapMode
	cef_win_GetMonitorInfo
	cef_win_GetDpiForMonitor
	cef_win_GetObject
	cef_win_GetParent
	cef_win_GetProp
	cef_win_GetRgnBox
	cef_win_GetROP2
	cef_win_GetScrollInfo
	cef_win_GetStockObject
	cef_win_GetSysColor
	cef_win_GetSysColorBrush
	cef_win_GetSystemMetrics
	cef_win_GetTextColor
	cef_win_GetTextExtentExPoint
	cef_win_GetTextExtentPoint
	cef_win_GetTextExtentPoint32
	cef_win_GetTextMetrics
	cef_win_GetViewPortExtEx
	cef_win_GetViewPortOrgEx
	cef_win_GetWindowExtEx
	cef_win_GetWindowLong
	cef_win_GetWindowRect
	cef_win_GetWindowSize
	cef_win_GetWindowOrgEx
	cef_win_GradientFill
	cef_win_HideCaret
	cef_win_InitializeCriticalSection
	cef_win_IntersectClipRect
	cef_win_InvalidateRect
	cef_win_InvalidateRgn
	cef_win_IsDBCSLeadByte
	cef_win_IsIconic
	cef_win_IsWindow
	cef_win_IsWindowEnabled
	cef_win_IsWindowVisible
	cef_win_IsZoomed
	cef_win_LeaveCriticalSection
	cef_win_LineTo
	cef_win_LoadBitmap
	cef_win_LoadIcon
	cef_win_MaskBltRop
	cef_win_MaskBlt
	cef_win_MessageBox
	cef_win_MonitorFromPoint
	cef_win_MonitorFromRect
	cef_win_MonitorFromWindow
	cef_win_MoveToEx
	cef_win_OffsetRgn
	cef_win_PaintRgn
	cef_win_Pie
	cef_win_PolyBezier
	cef_win_Polygon
	cef_win_Polyline
	cef_win_PostMessage
	cef_win_RealizePalette
	cef_win_Rectangle
	cef_win_RectInRegion
	cef_win_RectVisible
	cef_win_RedrawWindow
	cef_win_ReleaseCapture
	cef_win_ReleaseDC
	cef_win_RemoveProp
	cef_win_RestoreDC
	cef_win_RoundRect
	cef_win_SaveDC
	cef_win_ScrollWindowEx
	cef_win_SelectClipRGN
	cef_win_SelectObject
	cef_win_SelectPalette
	cef_win_SendMessage
	cef_win_SetActiveWindow
	cef_win_SetBkColor
	cef_win_SetBkMode
	cef_win_SetCapture
	cef_win_SetCaretPos
	cef_win_SetCaretPosEx
	cef_win_SetCursorPos
	cef_win_SetFocus
	cef_win_SetForegroundWindow
	cef_win_SetMapMode
	cef_win_SetMenu
	cef_win_SetParent
	cef_win_SetProp
	cef_win_SetROP2
	cef_win_SetScrollInfo
	cef_win_SetStretchBltMode
	cef_win_SetTextCharacterExtra
	cef_win_SetTextColor
	cef_win_SetWindowLong
	cef_win_SetViewPortExtEx
	cef_win_SetViewPortOrgEx
	cef_win_SetWindowExtEx
	cef_win_SetWindowOrgEx
	cef_win_SetWindowPos
	cef_win_ShowCaret
	cef_win_ShowScrollBar
	cef_win_ShowWindow
	cef_win_StretchBlt
	cef_win_StretchDIBits
	cef_win_SystemParametersInfo
	cef_win_TextOut
	cef_win_UpdateWindow
	cef_win_WindowFromPoint
	cef_win_GetWindowLongPtr
	cef_win_SetWindowLongPtr
	cef_win_GetClassLongPtr
	cef_win_SetClassLongPtr
	cef_win_FindWindow
	cef_win_FindWindowEx
	cef_win_SetWindowText
	cef_win_GetWindowText
	cef_win_GetWindowTextLength
) //end
