//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License Version 2.0, January 2004
//
// https://www.apache.org/licenses/LICENSE-2.0
//
//----------------------------------------

//go:build linux

package wv

import (
	"bytes"
	"encoding/json"
	"github.com/energye/energy/v3/internal/ipc"
	"github.com/energye/energy/v3/window"
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"
	wv "github.com/energye/wv/linux"
	wvTypes "github.com/energye/wv/types/linux"
	"runtime"
)

var (
	frameWidth  = 4
	frameHeight = 4
	frameCorner = frameWidth + frameHeight
)

type TWebview struct {
	lcl.IPanel
	browserId               uint32
	isClose                 bool
	isCreated               bool
	window                  window.IWindow
	windowParent            wv.IWkWebviewParent
	browser                 wv.IWkWebview
	settings                wv.IWkSettings
	messageReceivedDelegate ipc.IMessageReceivedDelegate
	onAfterCreated          lcl.TNotifyEvent
	onWindowClose           lcl.TCloseEvent
	onWindowShow            lcl.TNotifyEvent
	onWindowDestroy         lcl.TNotifyEvent
	//onWebMessageReceived          wv.TOnWebMessageReceivedEvent
	//onContextMenuRequested        wv.TOnContextMenuRequestedEvent
	//onContentLoading              wv.TOnContentLoadingEvent
	//onWebResourceRequested        TOnWebResourceRequestedEvent
	//onWebResourceResponseReceived TOnWebResourceResponseReceivedEvent
}

// NewWebview 创建一个新的浏览器窗口实例
func NewWebview(owner lcl.IComponent) IWebview {
	m := &TWebview{browserId: getNextBrowserID()}
	m.IPanel = lcl.NewPanel(owner)
	m.IPanel.SetParentColor(true)
	m.IPanel.SetParentDoubleBuffered(true)
	m.IPanel.SetBevelInner(types.BvNone)
	m.IPanel.SetBevelOuter(types.BvNone)

	m.windowParent = wv.NewWebviewParent(m)
	m.windowParent.SetParent(m)
	m.windowParent.SetAlign(types.AlClient)
	m.windowParent.SetParentDoubleBuffered(true)

	m.browser = wv.NewWebview(m)
	m.browser.RegisterScriptMessageHandler("processMessage")

	m.settings = wv.NewSettings()
	m.settings.SetEnableDeveloperExtras(true)
	m.settings.SetUserAgentWithApplicationDetails("energy.io", "3.0")
	m.settings.SetEnablePageCache(true)
	// 需要动态判断当前系统环境是否支持？
	m.settings.SetHardwareAccelerationPolicy(wvTypes.WEBKIT_HARDWARE_ACCELERATION_POLICY_NEVER)
	//setting.SetHardwareAccelerationPolicy(wvTypes.WEBKIT_HARDWARE_ACCELERATION_POLICY_ALWAYS)
	m.browser.SetSettings(m.settings)
	// ipc message received
	m.messageReceivedDelegate = ipc.NewMessageReceivedDelegate()
	ipc.RegisterProcessMessage(m)
	m.initDefaultEvent()
	m.SetBrowserOptions()
	return m
}

func (m *TWebview) SetWindow(window window.IWindow) {
	m.window = window
	if m.window != nil {
		if m.window.BrowserId() == 0 {
			m.window.SetBrowserId(m.browserId)
		}
		m.window.SetOptions()
	}
}

// SetBrowserOptions 设置浏览器窗口的选项配置
func (m *TWebview) SetBrowserOptions() {
	options := gApplication.Options
	if options.DefaultURL != "" {
		m.browser.LoadURL(options.DefaultURL)
	}
}

// SetParent 设置浏览器窗口的父控件
// 该方法会同时设置内部面板的父控件和窗口父控件的引用
func (m *TWebview) SetParent(window lcl.IWinControl) {
	m.IPanel.SetParent(window)
	m.windowParent.SetParent(m.IPanel)
}

// 在窗口显示时调用
func (m *TWebview) CreateBrowser() {
	if m.isCreated {
		return
	}
	m.isCreated = true
	m.browser.CreateBrowser()
	m.windowParent.SetWebview(m.browser)
}

// BrowserId Window ID, generated by accumulating sequence numbers
func (m *TWebview) BrowserId() uint32 {
	return m.browserId
}

func (m *TWebview) SendMessage(payload []byte) {
	if m.isClose {
		return
	}
	m.browser.ExecuteScript(string(payload))
}

func (m *TWebview) Close() {
	m.isClose = true
	m.windowParent.Free()
	ipc.UnRegisterProcessMessage(m)
}

func (m *TWebview) SetDefaultURL(url string) {
	m.browser.LoadURL(url)
}

func (m *TWebview) LoadURL(url string) {
	m.browser.LoadURL(url)
}

func (m *TWebview) SetOnAfterCreated(fn lcl.TNotifyEvent) {
	m.onAfterCreated = fn
}

func (m *TWebview) SetOnWindowClose(fn lcl.TCloseEvent) {
	m.onWindowClose = fn
}

func (m *TWebview) SetOnWindowShow(fn lcl.TNotifyEvent) {
	m.onWindowShow = fn
}

func (m *TWebview) SetOnWindowDestroy(fn lcl.TNotifyEvent) {
	m.onWindowDestroy = fn
}

func (m *TWebview) navigationStarting() {
	jsCode := &bytes.Buffer{}
	var envJS = func(json string) {
		jsCode.WriteString(`window.energy.setOptionsEnv(`)
		jsCode.WriteString(json)
		jsCode.WriteString(`);`)
	}
	optionsJSON, err := json.Marshal(gApplication.Options)
	if err == nil {
		envJS(string(optionsJSON))
	}
	env := make(map[string]any)
	env["frameWidth"] = frameWidth
	env["frameHeight"] = frameHeight
	env["frameCorner"] = frameCorner
	env["os"] = runtime.GOOS
	envJSON, err := json.Marshal(env)
	if err == nil {
		envJS(string(envJSON))
	}
	m.browser.ExecuteScript(jsCode.String())
	m.browser.ExecuteScript(`window.energy.drag().setup();`)
}

func (m *TWebview) initDefaultEvent() {

}
