//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License Version 2.0, January 2004
//
// https://www.apache.org/licenses/LICENSE-2.0
//
//----------------------------------------

//go:build linux

package wv

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/energye/energy/v3/internal/ipc"
	"github.com/energye/energy/v3/pkgs/mime"
	"github.com/energye/energy/v3/window"
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"
	wv "github.com/energye/wv/linux"
	wvTypes "github.com/energye/wv/types/linux"
	"runtime"
	"unsafe"
)

var (
	frameWidth  = int32(4)
	frameHeight = int32(4)
	frameCorner = frameWidth + frameHeight
)

type TWebview struct {
	lcl.ICustomPanel
	browserId               uint32
	isClose                 bool
	isCreated               bool
	window                  window.IWindow
	windowParent            wv.IWkWebviewParent
	browser                 wv.IWkWebview
	settings                wv.IWkSettings
	messageReceivedDelegate ipc.IMessageReceivedDelegate
	onAfterCreated          lcl.TNotifyEvent
	onWindowClose           lcl.TCloseEvent
	onWindowShow            lcl.TNotifyEvent
	onWindowDestroy         lcl.TNotifyEvent
	onProcessMessage        TOnProcessMessageEvent
	onResourceRequest       TOnResourceRequestEvent
	//onContextMenuRequested        wv.TOnContextMenuRequestedEvent
	//onContentLoading              wv.TOnContentLoadingEvent
	//onWebResourceRequested        TOnWebResourceRequestedEvent
	//onWebResourceResponseReceived TOnWebResourceResponseReceivedEvent
}

// NewWebview 创建一个新的浏览器窗口实例
func NewWebview(owner lcl.IComponent) IWebview {
	m := &TWebview{browserId: getNextBrowserID()}
	m.ICustomPanel = lcl.NewPanel(owner)
	m.ICustomPanel.SetParentDoubleBuffered(true)
	m.ICustomPanel.SetBevelInner(types.BvNone)
	m.ICustomPanel.SetBevelOuter(types.BvNone)

	m.windowParent = wv.NewWebviewParent(m)
	m.windowParent.SetWidth(m.Width())
	m.windowParent.SetHeight(m.Height())
	m.windowParent.SetAnchors(types.NewSet(types.AkLeft, types.AkTop, types.AkRight, types.AkBottom))
	m.windowParent.SetParentDoubleBuffered(true)

	m.browser = wv.NewWebview(owner)
	if gWk2Context == nil {
		gWk2Context = wv.WebContext.Default()
	}
	if gApplication.onCustomSchemes != nil {
		customSchemes := &TCustomSchemes{}
		gApplication.onCustomSchemes(customSchemes)
		for _, scheme := range customSchemes.schemes {
			gWk2Context.RegisterURIScheme(scheme.Scheme, m.browser.AsSchemeRequestDelegate())
		}
	}
	if gApplication.LocalLoad != nil {
		gWk2Context.RegisterURIScheme(gApplication.LocalLoad.Scheme, m.browser.AsSchemeRequestDelegate())
	}
	m.browser.RegisterScriptCode(string(ipcJS))
	m.browser.RegisterScriptMessageHandler("processMessage")

	m.settings = wv.NewSettings()
	m.settings.SetEnableDeveloperExtras(true)
	m.settings.SetUserAgentWithApplicationDetails("energy", "3.0")
	m.settings.SetEnablePageCache(true)
	// 需要动态判断当前系统环境是否支持？
	m.settings.SetHardwareAccelerationPolicy(wvTypes.WEBKIT_HARDWARE_ACCELERATION_POLICY_NEVER)
	//setting.SetHardwareAccelerationPolicy(wvTypes.WEBKIT_HARDWARE_ACCELERATION_POLICY_ALWAYS)
	m.browser.SetSettings(m.settings)
	// ipc message received
	m.messageReceivedDelegate = ipc.NewMessageReceivedDelegate()
	ipc.RegisterProcessMessage(m)
	m.initDefaultEvent()
	m.SetBrowserOptions()
	return m
}

//func (m *TWebview) SetAlign(v types.TAlign) {
//	switch v {
//	case types.AlClient:
//		part := m.Parent()
//		m.SetWidth(part.Width())
//		m.SetHeight(part.Height())
//		m.SetAnchors(types.NewSet(types.AkLeft, types.AkTop, types.AkRight, types.AkBottom))
//	default:
//		m.ICustomPanel.SetAlign(v)
//	}
//}

func (m *TWebview) SetWidth(v int32) {
	m.ICustomPanel.SetWidth(v + 1) // Gtk3 box width + 1
	m.windowParent.SetWidth(v)
}

func (m *TWebview) SetHeight(v int32) {
	m.ICustomPanel.SetHeight(v + 1) // Gtk3 box height + 1
	m.windowParent.SetHeight(v)
}

func (m *TWebview) SetWindow(window window.IWindow) {
	m.window = window
	if m.window != nil {
		if m.window.BrowserId() == 0 {
			m.window.SetBrowserId(m.browserId)
		}
		m.window.SetOptions()
	}
}

// SetBrowserOptions 设置浏览器窗口的选项配置
func (m *TWebview) SetBrowserOptions() {
	options := gApplication.Options
	if options.DefaultURL != "" {
		m.browser.LoadURL(options.DefaultURL)
	}
}

// SetParent 设置浏览器窗口的父控件
// 该方法会同时设置内部面板的父控件和窗口父控件的引用
func (m *TWebview) SetParent(window lcl.IWinControl) {
	m.ICustomPanel.SetParent(window)
	m.windowParent.SetParent(m)
}

// 在窗口显示时调用
func (m *TWebview) CreateBrowser() {
	if m.isCreated {
		return
	}
	m.isCreated = true
	m.browser.CreateBrowser()
	m.windowParent.SetWebview(m.browser)
}

// BrowserId Window ID, generated by accumulating sequence numbers
func (m *TWebview) BrowserId() uint32 {
	return m.browserId
}

func (m *TWebview) SendMessage(payload []byte) {
	if m.isClose {
		return
	}
	js := m.evalExecuteEventJS(payload)
	m.browser.ExecuteScript(js)
}

func (m *TWebview) evalExecuteEventJS(js []byte) string {
	evalJS := "if (typeof window.energy !== 'undefined' && typeof window.energy.__executeEvent === 'function') {window.energy.__executeEvent('" + string(js) + "');}"
	return evalJS
}

func (m *TWebview) Close() {
	m.isClose = true
	m.windowParent.Free()
	ipc.UnRegisterProcessMessage(m)
}

func (m *TWebview) SetDefaultURL(url string) {
	m.browser.LoadURL(url)
}

func (m *TWebview) LoadURL(url string) {
	m.browser.LoadURL(url)
}

func (m *TWebview) SetOnAfterCreated(fn lcl.TNotifyEvent) {
	m.onAfterCreated = fn
}

func (m *TWebview) SetOnWindowClose(fn lcl.TCloseEvent) {
	m.onWindowClose = fn
}

func (m *TWebview) SetOnWindowShow(fn lcl.TNotifyEvent) {
	m.onWindowShow = fn
}

func (m *TWebview) SetOnWindowDestroy(fn lcl.TNotifyEvent) {
	m.onWindowDestroy = fn
}

func (m *TWebview) SetOnResourceRequest(fn TOnResourceRequestEvent) {
	m.onResourceRequest = fn
}

func (m *TWebview) SetOnProcessMessage(fn TOnProcessMessageEvent) {
	m.onProcessMessage = fn
}

func (m *TWebview) navigationStarting() {
	jsCode := &bytes.Buffer{}
	var envJS = func(json string) {
		jsCode.WriteString(`window.energy.setOptionsEnv(`)
		jsCode.WriteString(json)
		jsCode.WriteString(`);`)
	}
	optionsJSON, err := json.Marshal(gApplication.Options)
	if err == nil {
		envJS(string(optionsJSON))
	}
	env := make(map[string]any)
	env["frameWidth"] = frameWidth
	env["frameHeight"] = frameHeight
	env["frameCorner"] = frameCorner
	env["os"] = runtime.GOOS
	envJSON, err := json.Marshal(env)
	if err == nil {
		envJS(string(envJSON))
	}
	m.browser.ExecuteScript(jsCode.String())
	m.browser.ExecuteScript(`window.energy.drag().setup();`)
}

func (m *TWebview) initDefaultEvent() {
	m.browser.SetOnLoadChange(func(sender lcl.IObject, loadEvent wvTypes.WebKitLoadEvent) {
		fmt.Println("OnLoadChange wkLoadEvent:", loadEvent)
		switch loadEvent {
		case wvTypes.WEBKIT_LOAD_FINISHED:
			m.navigationStarting()
		}
	})
	m.browser.SetOnContextMenu(func(sender lcl.IObject, contextMenu wvTypes.WebKitContextMenu, defaultAction wvTypes.PWkAction) bool {
		fmt.Println("OnContextMenu defaultAction:", defaultAction)
		tempContextMenu := wv.NewContextMenu(contextMenu)
		defer tempContextMenu.Free()
		tempMenuItemSep := wv.ContextMenuItem.NewSeparator()
		defer tempMenuItemSep.Free()
		tempContextMenu.Append(tempMenuItemSep.Data())
		tempMenuItemClose := wv.ContextMenuItem.NewFromAction(defaultAction, "关闭", 10001)
		defer tempMenuItemClose.Free()
		tempContextMenu.Append(tempMenuItemClose.Data())
		return false
	})
	m.browser.SetOnContextMenuCommand(func(sender lcl.IObject, menuID int32) {
		fmt.Println("OnContextMenuCommand menuID:", menuID)
		if menuID == 10001 {

		}
	})
	m.browser.SetOnWebProcessTerminated(func(sender lcl.IObject, reason wvTypes.WebKitWebProcessTerminationReason) {
		fmt.Println("OnWebProcessTerminated reason:", reason)
		if reason == wvTypes.WEBKIT_WEB_PROCESS_TERMINATED_BY_API { //  call m.webview.TerminateWebProcess()
			lcl.RunOnMainThreadAsync(func(id uint32) {
				m.Close()
			})
		}
	})
	m.browser.SetOnProcessMessage(func(sender lcl.IObject, jsValue wv.IWkJSValue, processId wvTypes.TWkProcessId) {
		var handle bool
		message := jsValue.StringValue()
		if m.messageReceivedDelegate != nil {
			fmt.Println("message:", message)
			// ipc message
			var pMessage ipc.ProcessMessage
			err := json.Unmarshal([]byte(message), &pMessage)
			if err == nil {
				switch pMessage.Type {
				case ipc.MT_READY:
					// ipc ready
					handle = true
				case ipc.MT_EVENT_GO_EMIT, ipc.MT_EVENT_JS_EMIT, ipc.MT_EVENT_GO_EMIT_CALLBACK, ipc.MT_EVENT_JS_EMIT_CALLBACK:
					// ipc on, emit event
					handle = m.messageReceivedDelegate.Received(m.BrowserId(), &pMessage)
				case ipc.MT_DRAG_MOVE, ipc.MT_DRAG_DOWN, ipc.MT_DRAG_UP, ipc.MT_DRAG_DBLCLICK:
					// ipc drag window
					if m.window != nil {
						m.browser.StartDrag(m.window)
						handle = true
					}
				case ipc.MT_DRAG_RESIZE:
					// border drag resize
					if m.window != nil {
						ht := pMessage.Data.(string)
						m.window.Resize(ht)
						handle = true
					}
				case ipc.MT_DRAG_BORDER_WMSZ:
					//fmt.Println("pMessage.Data", pMessage.Data)
					//m._SetCursor(17)
				}
			}
		}
		if !handle && m.onProcessMessage != nil {
			m.onProcessMessage(message)
		}
	})
	m.browser.SetOnDecidePolicy(func(sender lcl.IObject, wkDecision wvTypes.WebKitPolicyDecision, type_ wvTypes.WebKitPolicyDecisionType) bool {
		fmt.Println("OnDecidePolicy type_:", type_)
		tempDecision := wv.NewNavigationPolicyDecision(wkDecision)
		defer tempDecision.Free()
		if type_ == wvTypes.WEBKIT_POLICY_DECISION_TYPE_NEW_WINDOW_ACTION || type_ == wvTypes.WEBKIT_POLICY_DECISION_TYPE_NAVIGATION_ACTION {
			tempNavigationAction := wv.NewNavigationAction(tempDecision.GetNavigationAction())
			defer tempNavigationAction.Free()
			tempURIRequest := wv.NewURIRequest(tempNavigationAction.GetRequest())
			defer tempURIRequest.Free()
			newWindowURL := tempURIRequest.URI()
			fmt.Println("NewWindow URL:", newWindowURL)
			// new window
			if type_ == wvTypes.WEBKIT_POLICY_DECISION_TYPE_NEW_WINDOW_ACTION {

			}
		} else {
			tempResponsePolicyDecision := wv.NewResponsePolicyDecision(wkDecision)
			defer tempResponsePolicyDecision.Free()
			tempURIRequest := wv.NewURIRequest(tempResponsePolicyDecision.GetRequest())
			defer tempURIRequest.Free()
		}
		return true
	})
	m.browser.SetOnURISchemeRequest(func(sender lcl.IObject, wkURISchemeRequest wvTypes.WebKitURISchemeRequest) {
		uriSchemeRequest := wv.NewURISchemeRequest(wkURISchemeRequest)
		defer uriSchemeRequest.Free()
		var (
			resource    string
			handle      bool
			uri         = uriSchemeRequest.Uri()
			path        = uriSchemeRequest.Path()
			method      = uriSchemeRequest.Method()
			contentType = "Content-Type: " + mime.GetMimeType(path)
		)
		if m.onResourceRequest != nil {
			header := make(map[string]string)
			headers := wv.NewHeaders(uriSchemeRequest.Headers())
			defer headers.Free()
			headList := headers.List()
			if headList != nil {
				defer headList.Free()
				count := int(headList.Count())
				for i := 0; i < count; i++ {
					key := headList.Names(int32(i))
					val := headList.Values(key)
					header[key] = val
				}
			}
			resource, handle = m.onResourceRequest(uri, path, method, header)
		}
		if !handle {
			data, err := gApplication.LocalLoad.Read(path)
			if err != nil {
				// 404
				uriSchemeRequest.FinishError(3, 404, err.Error())
				return
			}
			ins := wv.InputStream.New(uintptr(unsafe.Pointer(&data[0])), int64(len(data)))
			uriSchemeRequest.Finish(ins.Data(), int64(len(data)), contentType)
		} else if handle && resource != "" {
			data := []byte(resource)
			ins := wv.InputStream.New(uintptr(unsafe.Pointer(&data[0])), int64(len(data)))
			uriSchemeRequest.Finish(ins.Data(), int64(len(data)), contentType)
		} else {
			// 404
			uriSchemeRequest.FinishError(3, 404, "Not Found")
		}
	})
	var (
		cursor    bool
		setCursor = func(value types.TCursor) {
			if value == types.CrDefault {
				cursor = false
			} else {
				cursor = true
			}
			lcl.Screen.SetCursor(value)
		}
	)
	m.browser.SetOnMouseMove(func(sender lcl.IObject, event wv.TWkButtonEvent) bool {
		fmt.Println("SetOnMouseMove:", event.X, event.Y, event.XRoot, event.YRoot, lcl.Screen.Cursor())
		br := m.window.BoundsRect()
		w, h := br.Width(), br.Height()
		x, y := event.X, event.Y
		leftBorder := x < frameWidth
		topBorder := y < frameHeight
		rightBorder := w-x < frameWidth
		bottomBorder := h-y < frameHeight
		leftCorner := x < frameWidth+frameCorner
		topCorner := y < frameHeight+frameCorner
		rightCorner := w-x < frameWidth+frameCorner
		bottomCorner := h-y < frameHeight+frameCorner
		if !leftBorder && !topBorder && !rightBorder && !bottomBorder {
			setCursor(types.CrDefault)
		} else if rightCorner && bottomCorner {
			setCursor(types.CrSizeSE)
		} else if leftCorner && bottomCorner {
			setCursor(types.CrSizeSW)
		} else if leftCorner && topCorner {
			setCursor(types.CrSizeNW)
		} else if topCorner && rightCorner {
			setCursor(types.CrSizeNE)
		} else if leftBorder {
			setCursor(types.CrSizeW)
		} else if topBorder {
			setCursor(types.CrSizeN)
		} else if bottomBorder {
			setCursor(types.CrSizeS)
		} else if rightBorder {
			setCursor(types.CrSizeE)
		} else {
			setCursor(types.CrDefault)
		}
		return cursor
	})
	m.browser.SetOnMousePress(func(sender lcl.IObject, event wv.TWkButtonEvent) bool {
		fmt.Println("SetOnMousePress:", event.X, event.Y, event.XRoot, event.YRoot)
		if cursor {

		}
		return false
	})
	m.browser.SetOnMouseRelease(func(sender lcl.IObject, event wv.TWkButtonEvent) bool {
		fmt.Println("SetOnMouseRelease:", event.X, event.Y, event.XRoot, event.YRoot)
		return false
	})
}
