//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License Version 2.0, January 2004
//
// https://www.apache.org/licenses/LICENSE-2.0
//
//----------------------------------------

//go:build linux

package wv

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/energye/energy/v3/internal/ipc"
	"github.com/energye/energy/v3/window"
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"
	wv "github.com/energye/wv/linux"
	wvTypes "github.com/energye/wv/types/linux"
	"path/filepath"
	"runtime"
	"unsafe"
)

var (
	frameWidth  = 4
	frameHeight = 4
	frameCorner = frameWidth + frameHeight
)

type TWebview struct {
	lcl.IPanel
	browserId               uint32
	isClose                 bool
	isCreated               bool
	window                  window.IWindow
	windowParent            wv.IWkWebviewParent
	browser                 wv.IWkWebview
	settings                wv.IWkSettings
	messageReceivedDelegate ipc.IMessageReceivedDelegate
	onAfterCreated          lcl.TNotifyEvent
	onWindowClose           lcl.TCloseEvent
	onWindowShow            lcl.TNotifyEvent
	onWindowDestroy         lcl.TNotifyEvent
	onProcessMessage        TOnProcessMessageEvent
	//onContextMenuRequested        wv.TOnContextMenuRequestedEvent
	//onContentLoading              wv.TOnContentLoadingEvent
	//onWebResourceRequested        TOnWebResourceRequestedEvent
	//onWebResourceResponseReceived TOnWebResourceResponseReceivedEvent
	onResourceRequest TOnResourceRequest
}

// NewWebview 创建一个新的浏览器窗口实例
func NewWebview(owner lcl.IComponent) IWebview {
	m := &TWebview{browserId: getNextBrowserID()}
	m.IPanel = lcl.NewPanel(owner)
	m.IPanel.SetParentColor(true)
	m.IPanel.SetParentDoubleBuffered(true)
	m.IPanel.SetBevelInner(types.BvNone)
	m.IPanel.SetBevelOuter(types.BvNone)

	m.windowParent = wv.NewWebviewParent(m)
	m.windowParent.SetParent(m)
	m.windowParent.SetAlign(types.AlClient)
	m.windowParent.SetParentDoubleBuffered(true)

	m.browser = wv.NewWebview(m)
	if gWk2Context == nil {
		gWk2Context = wv.WebContext.Default()
	}
	if gApplication.onCustomSchemes != nil {
		customSchemes := &TCustomSchemes{}
		gApplication.onCustomSchemes(customSchemes)
		for _, scheme := range customSchemes.schemes {
			gWk2Context.RegisterURIScheme(scheme.Scheme, m.browser.AsSchemeRequestDelegate())
		}
	}
	m.browser.RegisterScriptCode(string(ipcJS))
	m.browser.RegisterScriptMessageHandler("processMessage")

	m.settings = wv.NewSettings()
	m.settings.SetEnableDeveloperExtras(true)
	m.settings.SetUserAgentWithApplicationDetails("energy.io", "3.0")
	m.settings.SetEnablePageCache(true)
	// 需要动态判断当前系统环境是否支持？
	m.settings.SetHardwareAccelerationPolicy(wvTypes.WEBKIT_HARDWARE_ACCELERATION_POLICY_NEVER)
	//setting.SetHardwareAccelerationPolicy(wvTypes.WEBKIT_HARDWARE_ACCELERATION_POLICY_ALWAYS)
	m.browser.SetSettings(m.settings)
	// ipc message received
	m.messageReceivedDelegate = ipc.NewMessageReceivedDelegate()
	ipc.RegisterProcessMessage(m)
	m.initDefaultEvent()
	m.SetBrowserOptions()
	return m
}

func (m *TWebview) SetWindow(window window.IWindow) {
	m.window = window
	if m.window != nil {
		if m.window.BrowserId() == 0 {
			m.window.SetBrowserId(m.browserId)
		}
		m.window.SetOptions()
	}
}

// SetBrowserOptions 设置浏览器窗口的选项配置
func (m *TWebview) SetBrowserOptions() {
	options := gApplication.Options
	if options.DefaultURL != "" {
		m.browser.LoadURL(options.DefaultURL)
	}
}

// SetParent 设置浏览器窗口的父控件
// 该方法会同时设置内部面板的父控件和窗口父控件的引用
func (m *TWebview) SetParent(window lcl.IWinControl) {
	m.IPanel.SetParent(window)
	m.windowParent.SetParent(m.IPanel)
}

// 在窗口显示时调用
func (m *TWebview) CreateBrowser() {
	if m.isCreated {
		return
	}
	m.isCreated = true
	m.browser.CreateBrowser()
	m.windowParent.SetWebview(m.browser)
}

// BrowserId Window ID, generated by accumulating sequence numbers
func (m *TWebview) BrowserId() uint32 {
	return m.browserId
}

func (m *TWebview) SendMessage(payload []byte) {
	if m.isClose {
		return
	}
	m.browser.ExecuteScript(string(payload))
}

func (m *TWebview) Close() {
	m.isClose = true
	m.windowParent.Free()
	ipc.UnRegisterProcessMessage(m)
}

func (m *TWebview) SetDefaultURL(url string) {
	m.browser.LoadURL(url)
}

func (m *TWebview) LoadURL(url string) {
	m.browser.LoadURL(url)
}

func (m *TWebview) SetOnAfterCreated(fn lcl.TNotifyEvent) {
	m.onAfterCreated = fn
}

func (m *TWebview) SetOnWindowClose(fn lcl.TCloseEvent) {
	m.onWindowClose = fn
}

func (m *TWebview) SetOnWindowShow(fn lcl.TNotifyEvent) {
	m.onWindowShow = fn
}

func (m *TWebview) SetOnWindowDestroy(fn lcl.TNotifyEvent) {
	m.onWindowDestroy = fn
}

func (m *TWebview) navigationStarting() {
	jsCode := &bytes.Buffer{}
	var envJS = func(json string) {
		jsCode.WriteString(`window.energy.setOptionsEnv(`)
		jsCode.WriteString(json)
		jsCode.WriteString(`);`)
	}
	optionsJSON, err := json.Marshal(gApplication.Options)
	if err == nil {
		envJS(string(optionsJSON))
	}
	env := make(map[string]any)
	env["frameWidth"] = frameWidth
	env["frameHeight"] = frameHeight
	env["frameCorner"] = frameCorner
	env["os"] = runtime.GOOS
	envJSON, err := json.Marshal(env)
	if err == nil {
		envJS(string(envJSON))
	}
	m.browser.ExecuteScript(jsCode.String())
	m.browser.ExecuteScript(`window.energy.drag().setup();`)
}

func (m *TWebview) initDefaultEvent() {
	m.browser.SetOnLoadChange(func(sender lcl.IObject, loadEvent wvTypes.WebKitLoadEvent) {
		fmt.Println("OnLoadChange wkLoadEvent:", loadEvent)

	})
	m.browser.SetOnContextMenu(func(sender lcl.IObject, contextMenu wvTypes.WebKitContextMenu, defaultAction wvTypes.PWkAction) bool {
		fmt.Println("OnContextMenu defaultAction:", defaultAction)
		tempContextMenu := wv.NewContextMenu(contextMenu)
		defer tempContextMenu.Free()
		tempMenuItemSep := wv.ContextMenuItem.NewSeparator()
		defer tempMenuItemSep.Free()
		tempContextMenu.Append(tempMenuItemSep.Data())
		tempMenuItemClose := wv.ContextMenuItem.NewFromAction(defaultAction, "关闭", 10001)
		defer tempMenuItemClose.Free()
		tempContextMenu.Append(tempMenuItemClose.Data())
		return false
	})
	m.browser.SetOnContextMenuCommand(func(sender lcl.IObject, menuID int32) {
		fmt.Println("OnContextMenuCommand menuID:", menuID)
		if menuID == 10001 {

		}
	})
	m.browser.SetOnWebProcessTerminated(func(sender lcl.IObject, reason wvTypes.WebKitWebProcessTerminationReason) {
		fmt.Println("OnWebProcessTerminated reason:", reason)
		if reason == wvTypes.WEBKIT_WEB_PROCESS_TERMINATED_BY_API { //  call m.webview.TerminateWebProcess()
			lcl.RunOnMainThreadAsync(func(id uint32) {
				m.Close()
			})
		}
	})
	m.browser.SetOnProcessMessage(func(sender lcl.IObject, jsValue wv.IWkJSValue, processId wvTypes.TWkProcessId) {
		var handle bool
		message := jsValue.StringValue()
		if m.messageReceivedDelegate != nil {
			// ipc message
			var pMessage ipc.ProcessMessage
			err := json.Unmarshal([]byte(message), &pMessage)
			if err == nil {
				switch pMessage.Type {
				case ipc.MT_READY:
					// ipc ready
					handle = true
				case ipc.MT_EVENT_GO_EMIT, ipc.MT_EVENT_JS_EMIT, ipc.MT_EVENT_GO_EMIT_CALLBACK, ipc.MT_EVENT_JS_EMIT_CALLBACK:
					// ipc on, emit event
					handle = m.messageReceivedDelegate.Received(m.BrowserId(), &pMessage)
				case ipc.MT_DRAG_MOVE, ipc.MT_DRAG_DOWN, ipc.MT_DRAG_UP, ipc.MT_DRAG_DBLCLICK:
					// ipc drag window
					if m.window != nil {
						m.window.Drag(pMessage)
						handle = true
					}
				case ipc.MT_DRAG_RESIZE:
					// border drag resize
					if m.window != nil {
						ht := pMessage.Data.(string)
						m.window.Resize(ht)
						handle = true
					}
				case ipc.MT_DRAG_BORDER_WMSZ:
					//fmt.Println("pMessage.Data", pMessage.Data)
					//m._SetCursor(17)
				}
			}
		}
		if !handle && m.onProcessMessage != nil {
			m.onProcessMessage(message)
		}
	})
	m.browser.SetOnURISchemeRequest(func(sender lcl.IObject, wkURISchemeRequest wvTypes.WebKitURISchemeRequest) {
		fmt.Println("OnURISchemeRequest")
		uriSchemeRequest := wv.NewURISchemeRequest(wkURISchemeRequest)
		defer uriSchemeRequest.Free()
		fmt.Println("uri:", uriSchemeRequest.Uri(), "method:", uriSchemeRequest.Method(), "path:", uriSchemeRequest.Path())
		path := uriSchemeRequest.Path()
		if path == "" {
			path = "index.html"
		}
		assetsPath := filepath.Join("assets", path)
		data, _ := resources.ReadFile(assetsPath)
		ins := wv.InputStream.New(uintptr(unsafe.Pointer(&data[0])), int64(len(data)))
		uriSchemeRequest.Finish(ins.Data(), int64(len(data)), "text/html")

		var handle bool
		if m.onResourceRequest != nil {
			handle = m.onWebResourceRequested(sender, webview, args)
		}
		if !handle && gApplication.LocalLoad != nil {
			lcl.RunOnMainThreadSync(func() {
				gApplication.LocalLoad.ResourceRequested(m.browser, webview, args)
			})
		}
	})
}
