//----------------------------------------
// The code is automatically generated by the generate-tool.
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

package lcl

import (
	"github.com/energye/energy/v2/api"
	"unsafe"
)

// IUnknown 底层接口
type IUnknown interface {
	Instance() uintptr
	UnsafeAddr() unsafe.Pointer
	IsValid() bool
	SetInstance(instance unsafe.Pointer)
	free(index int)
}

// Unknown 接口
type Unknown struct {
	instance unsafe.Pointer
}

func (m *Unknown) Instance() uintptr {
	if m.instance == nil {
		return 0
	}
	return uintptr(m.instance)
}

func (m *Unknown) UnsafeAddr() unsafe.Pointer {
	return m.instance
}

func (m *Unknown) IsValid() bool {
	if m == nil || m.instance == nil {
		return false
	}
	return true
}

func (m *Unknown) SetInstance(instance unsafe.Pointer) {
	m.instance = instance
}

func (m *Unknown) free(index int) {
	if m.instance != nil {
		api.LCL().SysCallN(index, m.Instance())
		m.instance = nil
	}
}
