//----------------------------------------
// The code is automatically generated by the GenlibLcl tool.
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

package api

// CustomWidgetSetInitialization
// 自定义组件初始化 Linux
func CustomWidgetSetInitialization() bool {
	if !canWidgetSetInit {
		r1 := customWidgetImport.SysCallN(0)
		canWidgetSetInit = GoBool(r1)
	}
	return canWidgetSetInit
}

// CustomWidgetSetFinalization
//
//	自定义组件销毁 Linux
func CustomWidgetSetFinalization() bool {
	if canWidgetSetInit {
		r1 := customWidgetImport.SysCallN(1)
		canWidgetSetInit = false
		return GoBool(r1)
	}
	return false
}
